### PR TITLE
Ui tabbing 153910058

### PR DESCRIPTION
**Pull request by ers1519**

### CODE REVIEW

**Comment by almoral** [comment]
Hey, I was testing this and I couldn't get to the 'filter' button in the mobile view. Also, I added a listener for the enter key when tabbing through the events. Otherwise the event gets highlighted but users can't open the quick view without using a mouse.

**Comment by ers1519** [comment]
@almoral Yes, you are the correct about the mobile piece with tabs. Thought of it not that long ago. Not sure how many people with tab through this on a mobile view, but you never know. Good catch.

About the listeners, you would need to add a few more on mobile. The button to active the filters, the X, Rest and See more results. They should all work by clicking enter. I would probably make this into its own story. What do you think?

**Comment by almoral** [comment]
Yeah we should make that it's own story. That might require a bit of work. I don't know if the 'see results' button should work when you press enter without it having focus.

**Comment by ers1519** [comment]
Once I get the tabbing to work on mobile and I'll make sure each button I mentioned above will have a clear focus style associated with it.

**Comment by almoral** [comment]
Alright but I was thinking of treating the 'see results' button like a submit button. When the user hits enter, it automatically triggers that. Unless one of the other buttons has focus.

**Comment by fiallega** [comment]
@ers1519 is this pull request ready to be merged ?

**Comment by ers1519** [comment]
@fiallega Not yet, no. There's still some additional changes I need to do on mobile. I'll try to have it ready by COB today. I'll let you know.

**Comment by ers1519** [comment]
@fiallega I forgot to commit and push my changes on Friday. It should be good to go now.

**Comment by fiallega** [comment]
@ers1519 @almoral there are conflicts. You guys should merge it since you know what is going on

**Pull request merged**
