### PR TITLE
Ui filters wrap filters on accordions 153863655

### PR DESCRIPTION
**Pull request by ers1519**
Made the filters into accordions using pure CSS.

### CODE REVIEW

**Comment by fiallega** [comment]
@ers1519 @almoral please merge (there are confilcts)

**Comment by almoral** [comment]
@ers1519 Hey this isn't working quite right. You can still tab to the items that are hidden and enter data. 

Also, it seems wrong to have the simplest input hidden (textbox) and leave the most complex components visible (checkboxes). If the point is to minimize user scrolling and/or hide the complexity this doesn't seem correct. 

One last thing, should we have the accordions open on mobile? The UI is dedicated to the filters at that point. It might be a good idea to have them open when the user goes into the filter mode.

**Comment by ers1519** [comment]
@almoral if you're not seeing the entire left, all the filter sections, with accordions then something is wrong with what you're looking out.

You correct about the tabbing. Looking into that now. I've never paid this much to tabbing ever :).

Moreover, I do agree with you when it comes to the accordions being opened when on mobile, however, that's a decision left up to COMM at this point. They specifically wanted accordions always.

**Comment by ers1519** [comment]
@almoral it seems like you might have deleted some of the wrong conflicts. I was about to do a new commit and couldn't because my branch was behind. Once I pulled the incoming changes that's when I saw only the first two sections in the filters, Filter By Date and Filter By Title, with accordions.

It shouldn't be a biggie since each section has the same CSS to make the accordions work.

**Pull request merged**
